### PR TITLE
Update the MIB CISCO-ENTITY-VENDORTYPE-OID-MIB

### PR DESCRIPTION
**Pull request by earendilfr**
the current version doesn't support the Cisco Nexus 9364C

I have follow the Wiki to push the PR but, for an unknown reason, I have a difference reports/cisco and reports/all...
Only the file CISCO-ENTITY-VENDORTYPE-OID-MIB.my has been updated

### CODE REVIEW

**Comment by inphobia** [comment]
something went very wrong here, reports/all seems to be empty. i'll have a look asap

**Comment by inphobia** [comment]
care to have a look at #95 to see if that covered your needs?
(updated a few more mibs while i was at it)

**Comment by earendilfr** [comment]
Hello,

Yes, this commit cover the MIB change.

Thanks a lot.

**Comment by inphobia** [comment]
note: netdisco-mibs 4.017 has been released with the updates mibs. running netdisco-deploy will update them.

**Pull request closed without merging**
