### PR TITLE
Extreme MIBs Update 2020

### PR DESCRIPTION
**Pull request by Disco402**

### CODE REVIEW

**Comment by Disco402** [comment]
Confirmed working correctly in my environment

**Comment by inphobia** [comment]
while i don't have extreme devices (well, i do since they bought aerohive) i'll try & review & merge this asap.

**Comment by Disco402** [comment]
@inphobia any updates on when this will be merged?

**Comment by tbcurtis** [comment]
I would like to see these MIBs updated as well. Any update?

**Comment by inphobia** [comment]
this seems to touch more as just extreme mibs. since i'm an extreme customer too i'll try & have a look what they're offering on their site. it could be that these changes are legit due to extreme buying up everything they can lately.

**Comment by inphobia** [comment]
reworked & merged via #157

**Pull request closed without merging**
