### PR TITLE
2 Additional VMware MIBS

### PR DESCRIPTION
**Pull request by hanserasmus**
Didn't see these two mibs in the original master branch, added them. Please note my comments in PR #25 with regards to updates of user documents etc.

### CODE REVIEW

**Comment by ollyg** [comment]
Unfortunately something strange is happening with the RFC MIB translation when either of these two VMware MIBs are imported. I would like @JeroenvIS to take a look if he can find the time.

**Comment by ollyg** [comment]
For example:

```diff
diff --git a/EXTRAS/reports/all b/EXTRAS/reports/all
index 17d10a8..42cfb40 100644
--- a/EXTRAS/reports/all
+++ b/EXTRAS/reports/all
@@ -1749,13 +1749,13 @@
         mgmt(2) type=0
           mib-2(1) type=0
             system(1) type=0
-              sysDescr(1) type=2 hint=255a
+              sysDescr(1) type=2
               sysObjectID(2) type=1
               sysUpTime(3) type=8
                 sysUpTimeInstance(0) type=0
-              sysContact(4) type=2 hint=255a
-              sysName(5) type=2 hint=255a
-              sysLocation(6) type=2 hint=255a
+              sysContact(4) type=2
+              sysName(5) type=2
+              sysLocation(6) type=2
               sysServices(7) type=3
               sysORLastChange(8) type=8
               sysORTable(9) type=0
```

**Comment by JeroenvIS** [comment]
Seems to be caused by the import of an older definition for DisplayString; the two added MIBs import it from RFC1213-MIB, but a newer definition exists in SNMPv2-TC. The other VMWARE MIBs already imported it from SNMPv2-TC.

**Comment by JeroenvIS** [comment]
Updated, merged and pushed... but now starting to doubt whether these MIBs are relevant at all :-/
Both files are essentially contained in VMWARE-OBSOLETE-MIB. Quoting from that:

> DESCRIPTION
     "This MIB module contains all previously published managed objects that have been made
      obsolete. The mib preserves OID mappings such that backward compatiblity is maintained"

...so I guess we can revert the merge and close this ticket.

**Comment by inphobia** [comment]
> Unfortunately something strange is happening with the RFC MIB translation when either of these two VMware MIBs are imported. I would like @JeroenvIS to take a look if he can find the time.

for later reference, this is likely a cosmetic issue depending on genxlate's parse order. see #104

**Pull request merged**
